[package]
name = "lakeroad-egglog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egglog = { git = "https://github.com/egraphs-good/egglog" }
log = "0.4.20"
regex = "1.10.2"
