name: Prune ghcr.io packages

# Controls when the workflow will run
on:
  schedule:
    # Runs every Sunday at 4am PT.
    - cron: '0 11 * * 0'
  workflow_dispatch:

jobs:
  prune:
    runs-on: ubuntu-latest

    steps:
    - name: GHCR Pruning
      # You may pin to the exact commit or the version.
      uses: vlaurin/action-ghcr-prune@3c4f76ff904f206ace31dab45f37eb7c5a8e3d37
      with:
        token: ${{ secrets.GHCR_PRUNE_PAT }}
        container: lakeroad
        dry-run: false
        older-than: 7
        keep-last: 3
        untagged: true
        tag-regex: "sha-.*"
